# Generated by Django 3.1.1 on 2020-09-20 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0004_auto_20200920_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchandiserapply',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
