# Generated by Django 3.1.1 on 2020-09-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0005_auto_20200920_0655'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.TextField(max_length=20, null=True)),
                ('school', models.TextField(max_length=20)),
                ('grade', models.IntegerField(default=1)),
                ('department', models.TextField(max_length=20)),
                ('applyContent', models.TextField(max_length=512)),
                ('subject', models.TextField(max_length=30)),
            ],
        ),
    ]
