# Generated by Django 3.1.1 on 2020-09-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0006_studentapply'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentapply',
            name='postId',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
