# Generated by Django 3.1.1 on 2020-09-20 11:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0007_studentapply_postid'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchandiserapply',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='merchandiserapply',
            name='price',
            field=models.IntegerField(default=1),
        ),
    ]
