# Generated by Django 3.1.1 on 2020-09-20 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0008_auto_20200920_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchandiserapply',
            name='location',
            field=models.TextField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
