# Generated by Django 3.1.1 on 2020-09-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0010_merchandiserapply_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentapply',
            name='contact',
        ),
        migrations.AddField(
            model_name='studentapply',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='studentapply',
            name='title',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='studentapply',
            name='grade',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='studentapply',
            name='postId',
            field=models.IntegerField(null=True),
        ),
    ]
