# Generated by Django 3.1.1 on 2020-09-17 17:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilemer',
            old_name='userEmail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='profilemer',
            old_name='nickName',
            new_name='fullname',
        ),
        migrations.RenameField(
            model_name='profilestu',
            old_name='userSchool',
            new_name='bank',
        ),
        migrations.RenameField(
            model_name='profilestu',
            old_name='userMajor',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='profilestu',
            old_name='userEmail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='profilestu',
            old_name='nickName',
            new_name='fullname',
        ),
        migrations.RenameField(
            model_name='profilestu',
            old_name='userGrade',
            new_name='grade',
        ),
        migrations.RemoveField(
            model_name='profilemer',
            name='userMerchendise',
        ),
        migrations.AddField(
            model_name='profilemer',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profilemer',
            name='num1',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profilemer',
            name='num2',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profilemer',
            name='num3',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profilemer',
            name='photo',
            field=models.ImageField(default=1, upload_to='merchandiser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profilemer',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='profilestu',
            name='bank2',
            field=models.TextField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profilestu',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profilestu',
            name='school',
            field=models.TextField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profilestu',
            name='subject',
            field=models.TextField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profilestu',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
