# Generated by Django 3.1.1 on 2020-09-17 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200917_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemer',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='profilemer',
            name='title',
        ),
    ]
