# Generated by Django 3.1.1 on 2020-09-20 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200917_1748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilemer',
            old_name='fullname',
            new_name='fullname01',
        ),
        migrations.RenameField(
            model_name='profilestu',
            old_name='fullname',
            new_name='fullname02',
        ),
    ]
