# Generated by Django 3.1.1 on 2020-09-20 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200920_2023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilemer',
            old_name='fullname01',
            new_name='fullname',
        ),
        migrations.RenameField(
            model_name='profilestu',
            old_name='fullname02',
            new_name='fullname',
        ),
    ]
