# Generated by Django 3.1.1 on 2020-09-21 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20200921_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemer',
            name='category',
            field=models.CharField(choices=[('소상업체', '소상업체'), ('대학생', '대학생')], default='소상업체', max_length=10),
        ),
        migrations.AlterField(
            model_name='profilestu',
            name='category',
            field=models.CharField(choices=[('소상업체', '소상업체'), ('대학생', '대학생')], default='소상업체', max_length=10),
        ),
    ]
