# Generated by Django 3.1.1 on 2020-09-21 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20200921_2247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilemer',
            old_name='category',
            new_name='your_category',
        ),
        migrations.RenameField(
            model_name='profilestu',
            old_name='category',
            new_name='your_category',
        ),
    ]
