# Generated by Django 3.1.1 on 2020-09-14 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_auto_20200914_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pay',
            field=models.IntegerField(default=170),
        ),
    ]
