# Generated by Django 3.1.1 on 2020-09-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_auto_20200914_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pay',
            field=models.IntegerField(),
        ),
    ]
