# Generated by Django 3.1.1 on 2020-09-18 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_it_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IT',
        ),
        migrations.DeleteModel(
            name='video',
        ),
    ]
