# Generated by Django 3.1.1 on 2020-09-19 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0008_blog_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
