# Generated by Django 3.1.1 on 2020-09-19 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0010_auto_20200919_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('디자인', '디자인'), ('영상 및 사진', '영상 및 사진'), ('컨설팅', '컨설팅'), ('IT 및 프로그래밍', 'IT 및 프로그래밍')], default='디자인', max_length=10),
        ),
        migrations.AlterField(
            model_name='blog',
            name='pay',
            field=models.IntegerField(default=0),
        ),
    ]
