# Generated by Django 3.1.1 on 2020-09-19 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0011_auto_20200920_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pay',
            field=models.IntegerField(),
        ),
    ]
