# Generated by Django 3.1.1 on 2020-09-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0013_auto_20200921_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category2',
            field=models.CharField(choices=[('업체', '업체'), ('학생', '학생'), ('기타', '기타')], default='업체', max_length=10),
        ),
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('디자인', '디자인'), ('영상 및 사진', '영상 및 사진'), ('컨설팅', '컨설팅'), ('IT 및 프로그래밍', 'IT 및 프로그래밍')], default='디자인', max_length=10),
        ),
    ]
