# Generated by Django 3.1.1 on 2020-09-20 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0014_auto_20200921_0047'),
    ]

    operations = [
        migrations.CreateModel(
            name='StuApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('name', models.TextField()),
                ('spot', models.TextField()),
                ('date', models.DateField(blank=True)),
                ('pay', models.IntegerField()),
                ('category', models.CharField(choices=[('디자인', '디자인'), ('영상 및 사진', '영상 및 사진'), ('컨설팅', '컨설팅'), ('IT 및 프로그래밍', 'IT 및 프로그래밍')], default='디자인', max_length=10)),
                ('category2', models.CharField(choices=[('업체', '업체'), ('학생', '학생'), ('기타', '기타')], default='업체', max_length=10)),
            ],
        ),
    ]
