# Generated by Django 3.1.1 on 2020-09-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0015_stuapply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stuapply',
            old_name='spot',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='stuapply',
            old_name='pay',
            new_name='grade',
        ),
        migrations.RenameField(
            model_name='stuapply',
            old_name='title',
            new_name='major',
        ),
        migrations.RemoveField(
            model_name='stuapply',
            name='category',
        ),
        migrations.RemoveField(
            model_name='stuapply',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='stuapply',
            name='date',
        ),
        migrations.RemoveField(
            model_name='stuapply',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='stuapply',
            name='email',
            field=models.EmailField(default='likelion@inha.edu', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stuapply',
            name='school',
            field=models.CharField(default='undefine@example.com', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stuapply',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
