# Generated by Django 3.1.1 on 2020-09-20 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0016_auto_20200921_0330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stuapply',
            old_name='category2',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='stuapply',
            name='account',
            field=models.TextField(max_length=200),
        ),
    ]
