# Generated by Django 3.1.1 on 2020-09-20 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0018_auto_20200921_0332'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuapply',
            name='namestore',
            field=models.CharField(default='example', max_length=200),
            preserve_default=False,
        ),
    ]
